### ISSUE TITLE
More sensible rules for running code checks, image builds, etc. on PR

### ISSUE THREAD

**Issue by samthorold** [recipes-org/svc-recipes#11]

**Comment by samthorold** [comment]
Could be a job with outputs for what has changed e.g. `needs.changes.outputs.{src,docs,tests,ci,...}`

**Comment by samthorold** [comment]
If a change in workflow requires a new app, bump the minor version in the app.

**Comment by samthorold** [comment]
```yaml
on:
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "docs/**"
      - "tests/**"
      - ".github/workflows/docs-deploy.yaml"
```

and / or at the job level ([link](https://stackoverflow.com/questions/70708306/github-actions-run-step-job-in-a-workflow-if-changes-happen-in-specific-folde), [better link](https://how.wtf/run-workflow-step-or-job-based-on-file-changes-github-actions.html))
